name: bsky bot

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs: 
  post:
    runs-on: ubuntu-latest
    
    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
      
    steps:
    - uses: actions/checkout@v3
    
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: 'release'
        
    - name: Cache R packages
      uses: actions/cache@v3
      with:
        path: ${{ env.RENV_PATHS_ROOT }}
        key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-renv-
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libfontconfig1-dev libharfbuzz-dev libfribidi-dev

    - name: Install R packages
      working-directory: ./suncalc-bot
      run: |
        if (!require("renv")) install.packages("renv")
        renv::restore()
      shell: Rscript {0}
      
    - name: Run script
      working-directory: ./suncalc-bot
      env:
        BLUESKY_APP_PASS: ${{ secrets.BLUESKY_APP_PASS }}
      run: Rscript './post.R'
      
 # Add new files in data folder, commit along with other modified files, push
    - name: Commit files
      working-directory: ./suncalc-bot
      run: |
        git config --local user.name actions-user
        git config --local user.email "actions@github.com"
        git add '*'
        git commit -am "Actualización: $(date)"
        git push origin main
      env:
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}
        username: github-actions